# Generated by Django 3.2.7 on 2021-10-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('sezes', models.CharField(max_length=100, verbose_name='颜色')),
                ('types', models.CharField(max_length=100, verbose_name='类型')),
                ('price', models.FloatField(verbose_name='价格')),
                ('discount', models.FloatField(verbose_name='折后')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('sold', models.IntegerField(verbose_name='已售')),
                ('likes', models.IntegerField(verbose_name='收藏')),
                ('created', models.DateField(auto_now_add=True, verbose_name='上架日期')),
                ('img', models.FileField(upload_to='imgs', verbose_name='商品图')),
                ('details', models.FileField(upload_to='details', verbose_name='商品介绍')),
            ],
            options={
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firsts', models.CharField(max_length=100, verbose_name='一级分类')),
                ('seconds', models.CharField(max_length=100, verbose_name='二级分类')),
            ],
            options={
                'verbose_name_plural': '类型',
            },
        ),
    ]
