# Generated by Django 3.2.7 on 2021-10-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_alter_commodityinfos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfos',
            name='details',
            field=models.FileField(db_column='details', upload_to='details', verbose_name='商品介绍'),
        ),
    ]
